# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

ChallengeType.find_or_create_by(name: "Individual")
ChallengeType.find_or_create_by(name: "Team")

Intensity.find_or_create_by(name: "Low")
Intensity.find_or_create_by(name: "Medium")
Intensity.find_or_create_by(name: "High")
ExerciseUnit.find_or_create_by(name: "points")
ExerciseUnit.find_or_create_by(name: "calories")
ExerciseUnit.find_or_create_by(name: "miles")
ExerciseUnit.find_or_create_by(name: "kilometers")
ExerciseUnit.find_or_create_by(name: "steps")
ExerciseUnit.find_or_create_by(name: "minutes")

ExerciseType.find_or_create_by(name: "running")
ExerciseType.find_or_create_by(name: "walking")
ExerciseType.find_or_create_by(name: "biking")
ExerciseType.find_or_create_by(name: "yoga")
ExerciseType.find_or_create_by(name: "swimming")
ExerciseType.find_or_create_by(name: "baseball")
ExerciseType.find_or_create_by(name: "softball")
ExerciseType.find_or_create_by(name: "golf")
ExerciseType.find_or_create_by(name: "basketball")
ExerciseType.find_or_create_by(name: "football")
ExerciseType.find_or_create_by(name: "tennis")
ExerciseType.find_or_create_by(name: "weight lifting")
ExerciseType.find_or_create_by(name: "aerobics")
ExerciseType.find_or_create_by(name: "belly dancing")
ExerciseType.find_or_create_by(name: "zoomba")
ExerciseType.find_or_create_by(name: "martial arts")
ExerciseType.find_or_create_by(name: "dancing")
ExerciseType.find_or_create_by(name: "boxing")
ExerciseType.find_or_create_by(name: "canoeing")
ExerciseType.find_or_create_by(name: "hiking")
ExerciseType.find_or_create_by(name: "kayaking")
ExerciseType.find_or_create_by(name: "fishing")
ExerciseType.find_or_create_by(name: "moving")
ExerciseType.find_or_create_by(name: "mowing the lawn")
ExerciseType.find_or_create_by(name: "chores")
ExerciseType.find_or_create_by(name: "bodyweight exercises (push ups, pull ups, etc)")